server:
  port: 8081
  
spring:
  application:
    name: discipline-server
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:alunodb  
feign:
  hystrix:
    enabled: true
  command:
    StudentsClients:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 5
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
      circuitBreaker:
        requestVolumeThreshold: 5 

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

