server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file://home/juliano/Development/workspace/curso/voffice/voffice-microservice/config-repo