server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://home/juliano/Development/workspace/curso/voffice/voffice-microservice/cloud-lab04/config-repo


#  rabbitmq:
#    host: localhost
#    port: 5672
